AWS_ACCESS_KEY_ID     = ""
AWS_SECRET_ACCESS_KEY = ""
ami_name              = "CSYE-6225-assignment-4"
aws_region            = "us-east-1"
source_ami            = "ami-033b95fb8079dc481"
ssh_username          = "csye6225 cloud"
