# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Pull Request Check CI
on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install Node Packages
      run: npm ci 
    - name: Zip dependency file
      run: zip -r webservice.zip .
    - name: Packer Init
      uses: hashicorp/packer-github-actions@master
      with:
        command: init
        target: application-ami.pkr.hcl
    - name: Packer Validate
      uses: hashicorp/packer-github-actions@master
      with: 
        command: validate
        target: application-ami.pkr.hcl

